name: Deploy App Service with Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure Subscription
        run: az account set --subscription "8064129a-9dce-41ee-aa44-fc3d0a13a4ad"

      - name: ACR Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ vars.ACR_NAME }}.azurecr.io
          username: ${{ vars.ACR_NAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ vars.ACR_NAME }}.azurecr.io/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ vars.ACR_NAME }}.azurecr.io/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.sha }}

      - name: Debug - List Web Apps
        run: az webapp list --query "[].{Name:name, ResourceGroup:resourceGroup}" --output table

      - name: Deploy to Azure App Service (CLI)
        run: |
          az webapp config container set \
            --name ${{ vars.APP_SERVICE_NAME }} \
            --resource-group rg-tarea3-betty \
            --docker-custom-image-name ${{ vars.ACR_NAME }}.azurecr.io/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.sha }}
